name: Build action
on: [push]
jobs:
  Checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls -lah
  Build:
    with:
      dotnet-version: '5.0'
    run: dotnet --version
        