name: Build action
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls -lah
      - run: dotnet --version
      - run: dotnet publish -c Release -o ./publish
      - run: ls -lah ./publish